// This file is automatically generated. Do not edit.
declare namespace ProgressModuleCssModule {
  export interface IProgressModuleCss {
    bar: string;
    container: string;
    green: string;
    gutter: string;
    md: string;
    progress: string;
    red: string;
    themeGreen: string;
    themeRed: string;
    themeYellow: string;
    yellow: string;
  }
}

declare const ProgressModuleCssModule: ProgressModuleCssModule.IProgressModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProgressModuleCssModule.IProgressModuleCss;
};

export = ProgressModuleCssModule;
