// This file is automatically generated. Do not edit.
declare namespace ToggleModuleCssModule {
  export interface IToggleModuleCss {
    colorLightness: string;
    slider: string;
    themeBackground: string;
    themeGreen: string;
    themeGrey: string;
    toggle: string;
  }
}

declare const ToggleModuleCssModule: ToggleModuleCssModule.IToggleModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ToggleModuleCssModule.IToggleModuleCss;
};

export = ToggleModuleCssModule;
